import React from 'react'

const feeds = ({feed}) => {
  return (
    <div>
      <h1>
      <title>Create Feeds App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </h1>
      {
feed.map((item)=>(
    <div key={item.id}>{item.title}</div>
))
      }
    </div>
  )
}
export async function getServerSideProps(){
    const response=await fetch(` http://localhost:8080/feeds`)
    let data=await response.json();
    return {
        props:{
            feed:data
        }
    }
}

export default feeds
