import React, { useState } from 'react'

const counter = () => {
  const [count,setCount]=useState(0)
  return (
    <div>
     <h1>
        <title>Counter app By Suman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </h1>
      <h1>{count}</h1>
      <button disabled={count==0} onClick={()=>setCount(count-1)}>-</button>
      <button onClick={()=>setCount(count+1)}>+</button>
    </div>
  )
}

export default counter
