import React, { useEffect, useState } from 'react'

const todo = ({todos}) => {
   
  return (
    <div>
     <h1>
        <title>Todo app By Suman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </h1>
      {
        todos.map((item)=>(
            <div key={item.id}>{item.value}</div>
        ))
      }
    </div>
  )
}
export async function getServerSideProps(){
    const response=await fetch("http://localhost:8080/todos");
    let data=await response.json()
    return {
        props:{
            todos:data,
        }
    }
}
export default todo
