import React from 'react'
import Link from "next/link";

const Navbar = () => {
  return (
    <div>
      <h1>
      <title>Create Navbar App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </h1>
      <div style={{display:'flex',justifyContent:"space-around"}}>
        <Link href="/">Home</Link>
        <Link href="/feeds">Feeds</Link>
      </div>
    </div>
  )
}

export default Navbar
