import React from 'react';
import Head from "next/head";
import { useRouter } from 'next/router';
// import Image from 'next/image';

const Page = ({movies=[]}) => {
  const router = useRouter();

  const handleClick=(id)=>{
    console.log(id)
    router.push(`/${id}`)
  }

  return (
    <div>
    <Head>
   <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<main  style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",margin:"60px"}}>

{
     movies.map((movie)=>(
            
          <div key={movie.id} onClick={()=>handleClick(movie.id)} 
          >
           
           <img src={movie.Images[0]} alt={movie.Poster}  
           width={300}
        height={300}/>
            <h1 style={{marginLeft:"100px"}}>{movie.Title}</h1>
           
          </div>
        ))
      }
</main>
     
    </div>
  )
}
export async function getStaticProps() {
  let response=await fetch(`http://localhost:8080/movie`)
  let data=await response.json();

  return {
    props: {
      movies:data
    }, // will be passed to the page component as props
  }
}
export default Page
