import React from 'react';
import Head from "next/head";
import { useRouter } from 'next/router';
import Link from "next/link";

const Page = ({blogs=[]}) => {
  const router = useRouter()

  const handleClick=(id)=>{
    console.log(id)
    router.push(`/${id}`)
  }

  return (
    <div>
    <Head>
   <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<main>
{
        blogs.map((blog)=>(
          <div key={blog.id}>
           
            {/* <Link href={`/${blog.id}`}>{blog.title}</Link> */}
            <h1 onClick={()=>handleClick(blog.id)}>{blog.title}</h1>
            <p>{blog.description}</p>
          </div>
        ))
      }
</main>
     
    </div>
  )
}
export async function getServerSideProps() {
  let response=await fetch(`http://localhost:8080/blogs`)
  let data=await response.json();

  return {
    props: {
      blogs:data
    }, // will be passed to the page component as props
  }
}
export default Page
